### ISSUE TITLE
roslaunch tello_driver tello_node.launch   BUT: File "/home/smile/code_demo/tello_catkin_ws/src/tello_driver/src/tello_driver_node.py", line 14, in <module>     import av ImportError: No module named av

### ISSUE THREAD

**Issue by 10179013** [anqixu/tello_driver#21]
`smile@smile-Vostro-3400:~/code_demo/tello_catkin_ws$ roslaunch tello_driver tello_node.launch 
... logging to /home/smile/.ros/log/59a006b8-e9f1-11ec-8906-a4423b77d657/roslaunch-smile-Vostro-3400-10061.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://smile-Vostro-3400:37971/

SUMMARY
========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.13
 * /tello/tello/connect_timeout_sec: 10.0
 * /tello/tello/local_cmd_client_port: 8890
 * /tello/tello/local_vid_server_port: 6038
 * /tello/tello/stream_h264_video: False
 * /tello/tello/tello_cmd_server_port: 8889
 * /tello/tello/tello_ip: 192.168.10.1

NODES
  /tello/
    image_compressed (image_transport/republish)
    tello (tello_driver/tello_driver_node.py)

auto-starting new master
process[master]: started with pid [10071]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 59a006b8-e9f1-11ec-8906-a4423b77d657
process[rosout-1]: started with pid [10082]
started core service [/rosout]
process[tello/tello-2]: started with pid [10086]
process[tello/image_compressed-3]: started with pid [10089]
terminate called after throwing an instance of 'pluginlib::LibraryLoadException'
  what():  According to the loaded plugin descriptions the class image_transport/compressed_pub with base class type image_transport::PublisherPlugin does not exist. Declared types are  image_transport/raw_pub
Traceback (most recent call last):
  File "/home/smile/code_demo/tello_catkin_ws/src/tello_driver/src/tello_driver_node.py", line 14, in <module>
    import av
ImportError: No module named av
[tello/tello-2] process has died [pid 10086, exit code 1, cmd /home/smile/code_demo/tello_catkin_ws/src/tello_driver/src/tello_driver_node.py __name:=tello __log:=/home/smile/.ros/log/59a006b8-e9f1-11ec-8906-a4423b77d657/tello-tello-2.log].
log file: /home/smile/.ros/log/59a006b8-e9f1-11ec-8906-a4423b77d657/tello-tello-2*.log
[tello/image_compressed-3] process has died [pid 10089, exit code -6, cmd /opt/ros/melodic/lib/image_transport/republish raw in:=image_raw compressed out:=image_raw __name:=image_compressed __log:=/home/smile/.ros/log/59a006b8-e9f1-11ec-8906-a4423b77d657/tello-image_compressed-3.log].
log file: /home/smile/.ros/log/59a006b8-e9f1-11ec-8906-a4423b77d657/tello-image_compressed-3*.log
`

**Comment by 10179013** [comment]
`
smile@smile-Vostro-3400:~$ pip install av
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Defaulting to user installation because normal site-packages is not writeable
Collecting av
  Downloading av-9.2.0.tar.gz (2.4 MB)
     |████████████████████████████████| 2.4 MB 250 kB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python /home/smile/.local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpEjjUR3
       cwd: /tmp/pip-install-Kw4jkO/av
  Complete output (18 lines):
  Traceback (most recent call last):
    File "/home/smile/.local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/home/smile/.local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/smile/.local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-XzZKEb/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-XzZKEb/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-XzZKEb/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 243, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-XzZKEb/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 3, in <module>
      import pathlib
  ImportError: No module named pathlib
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python /home/smile/.local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpEjjUR3 Check the logs for full command output.
WARNING: You are using pip version 20.3.4; however, version 21.3.1 is available.
You should consider upgrading via the '/usr/bin/python -m pip install --upgrade pip' command.
smile@smile-Vostro-3400:~$ 

`

**Comment by 10179013** [comment]
`
smile@smile-Vostro-3400:~$ pip install av
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Defaulting to user installation because normal site-packages is not writeable
Collecting av
  Using cached av-9.2.0.tar.gz (2.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python /home/smile/.local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp_5eHT7
       cwd: /tmp/pip-install-L7zLhN/av
  Complete output (18 lines):
  Traceback (most recent call last):
    File "/home/smile/.local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/home/smile/.local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/smile/.local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-3Qqyn1/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-3Qqyn1/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-3Qqyn1/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 243, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-3Qqyn1/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 3, in <module>
      import pathlib
  ImportError: No module named pathlib
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python /home/smile/.local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp_5eHT7 Check the logs for full command output.
WARNING: You are using pip version 20.3.4; however, version 21.3.1 is available.
You should consider upgrading via the '/usr/bin/python -m pip install --upgrade pip' command.
smile@smile-Vostro-3400:~$ /usr/bin/python -m pip install --upgrade pip
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Defaulting to user installation because normal site-packages is not writeable
Requirement already up-to-date: pip in ./.local/lib/python2.7/site-packages (20.3.4)
WARNING: You are using pip version 20.3.4; however, version 21.3.1 is available.
You should consider upgrading via the '/usr/bin/python -m pip install --upgrade pip' command.
smile@smile-Vostro-3400:~$ sudo /usr/bin/python -m pip install --upgrade pip
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
WARNING: The directory '/home/smile/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already up-to-date: pip in ./.local/lib/python2.7/site-packages (20.3.4)
smile@smile-Vostro-3400:~$ sudo /usr/bin/python -m pip install --upgrade pip --user
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
WARNING: The directory '/home/smile/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already up-to-date: pip in ./.local/lib/python2.7/site-packages (20.3.4)

`

**Comment by habibmuhammadthariq** [comment]
In my case, installing av version 0.5.2 was worked.
you can try `pip install av=0.5.2`
