### ISSUE TITLE
 superclass doesn't expect arguments 

### ISSUE THREAD

**Issue by mgrallos** [anqixu/tello_driver#26]
Hi got this error after I change from python2 to python3 

```
line 77, in __init__
    super(TelloNode, self).__init__(
TypeError: __init__() got an unexpected keyword argument 'local_cmd_client_port' 
```

It seems like the __init__ function of the superclass doesn't expect the local_cmd_client_port argument. The argument is coming from this snippet 
```
super(TelloNode, self).__init__(
            local_cmd_client_port=self.local_cmd_client_port,
            local_vid_server_port=self.local_vid_server_port,
            tello_ip=self.tello_ip,
            tello_cmd_server_port=self.tello_cmd_server_port,
            log=log)

```

**Comment by jeonsion** [comment]
i got same issue plz help me

my setting is
(docker)
ros noetic
ubuntu 20.04

and i changed from python2 to 3 

```
root@cc506e2e2b5f:~/catkin_ws# roslaunch tello_driver tello_node.launch 
... logging to /root/.ros/log/4156f33e-3a48-11ee-a22e-0242ac110002/roslaunch-cc506e2e2b5f-38675.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://cc506e2e2b5f:43243/

SUMMARY
========

PARAMETERS
 * /rosdistro: noetic
 * /rosversion: 1.16.0
 * /tello/tello/connect_timeout_sec: 10.0
 * /tello/tello/local_cmd_client_port: 8890
 * /tello/tello/local_vid_server_port: 6038
 * /tello/tello/stream_h264_video: True
 * /tello/tello/tello_cmd_server_port: 8889
 * /tello/tello/tello_ip: 192.168.10.1

NODES
  /tello/
    image_compressed (image_transport/republish)
    tello (tello_driver/tello_driver_node.py)

ROS_MASTER_URI=http://localhost:11311

process[tello/tello-1]: started with pid [38696]
process[tello/image_compressed-2]: started with pid [38697]
Traceback (most recent call last):
  File "/root/catkin_ws/src/tello_driver/src/tello_driver_node.py", line 306, in <module>
    main()
  File "/root/catkin_ws/src/tello_driver/src/tello_driver_node.py", line 300, in main
    robot = TelloNode()
  File "/root/catkin_ws/src/tello_driver/src/tello_driver_node.py", line 76, in __init__
    super(TelloNode, self).__init__(
TypeError: __init__() got an unexpected keyword argument 'local_cmd_client_port'
[tello/tello-1] process has died [pid 38696, exit code 1, cmd /root/catkin_ws/src/tello_driver/src/tello_driver_node.py __name:=tello __log:=/root/.ros/log/4156f33e-3a48-11ee-a22e-0242ac110002/tello-tello-1.log].
log file: /root/.ros/log/4156f33e-3a48-11ee-a22e-0242ac110002/tello-tello-1*.log
^C[tello/image_compressed-2] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```
